// 拡張子→MIMEタイプ対応表（Phase 1 で app.js から抽出）。内容は不変。

export const extensionToMimeTypeMap = {
    // Text Data
    'pdf': 'application/pdf',
    'js': 'text/javascript',
    'py': 'text/x-python',
    'txt': 'text/plain',
    'html': 'text/html',
    'htm': 'text/html',
    'json': 'application/json',
    'css': 'text/css',
    'md': 'text/markdown',
    'csv': 'text/csv',
    'xml': 'application/xml',
    'rtf': 'application/rtf',
    'java': 'text/x-java-source',
    'c': 'text/x-c',
    'cpp': 'text/x-c++src',
    'hpp': 'text/x-c++hdr',
    'h': 'text/x-chdr',
    'cs': 'text/plain',
    'php': 'application/x-httpd-php',
    'rb': 'text/x-ruby',
    'go': 'text/x-go',
    'swift': 'text/x-swift',
    'kt': 'text/x-kotlin',
    'kts': 'text/x-kotlin',
    'rs': 'text/rust',
    'ts': 'text/typescript',
    'tsx': 'text/typescript',
    'sql': 'application/sql',
    'sh': 'application/x-sh',
    'yml': 'text/yaml',
    'yaml': 'text/yaml',

    // Image Data
    'png': 'image/png',
    'jpg': 'image/jpeg',
    'jpeg': 'image/jpeg',
    'webp': 'image/webp',
    'heic': 'image/heic',
    'heif': 'image/heif',

    // Video Data
    'mp4': 'video/mp4',
    'mpeg': 'video/mpeg',
    'mov': 'video/mov',
    'avi': 'video/avi',
    'flv': 'video/x-flv',
    'mpg': 'video/mpg',
    'webm': 'video/webm',
    'wmv': 'video/wmv',
    '3gp': 'video/3gpp',
    '3gpp': 'video/3gpp',

    // Audio Data
    'wav': 'audio/wav',
    'mp3': 'audio/mp3',
    'aiff': 'audio/aiff',
    'aac': 'audio/aac',
    'ogg': 'audio/ogg',
    'flac': 'audio/flac',
};
